# Site settings
title: Birdies Cafe
email: denise@birdiescafe.com
description: > # this means to ignore newlines until "baseurl:"
  Birdies Cafe is an Americana-themed restaurant in Bend, Oregon, serving breakfast and lunch 7 days a week.
baseurl: "/birdiescafe" # the subpath of your site, e.g. /blog/
url: "https://ajzeigert.github.io" # the base hostname & protocol for your site
twitter_username: birdiescafebend

# Build settings
markdown: kramdown
